# Minecraft 26.2 Version Properties
minecraft_version=26.2
# Fabric uses semver-style ranges, NeoForge uses Maven-style ranges
fabric_minecraft_version=>=26.2 <26.2.1
neoforge_minecraft_version=[26.2,26.2.1)

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.152.2+26.2

# NeoForge
neoforge_version=26.2.0.6-beta
